name: Faucetearner

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.8'  # Replace with the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Installs the requests library
        pip install rich
        pip install fake_useragent
        pip install bs4

    - name: Run Python script in a loop
      run: |
        while true; do python main.py; done
